feat: Expose log_analytics variable and create _Default bucket in TF …
mozilla/terraform-modules pull request #138
Opened 2023-10-18 15:07 UTC by Flipez

…if true

2023-10-18 15:24 UTC, jasonthomas commented
Since the logging bucket config is already provisioned automatically for projects for _Default and _Required buckets, (as per https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/logging_project_bucket_config), in your testing, does this require that the existing resource to be imported into state?

2023-10-18 16:22 UTC, jasonthomas commented
If the resource can just be created without an import (that is, we don't need to reconcile any config differences), I'd say we should just create `google_logging_project_bucket_config` resource without the condition on if `log_analytics` is enabled.

2023-10-19 12:57 UTC, Flipez commented
I was able to run tf and apply the changes to the bucket without reimporting a resource. If I change behavior as requested by you it will apply what looks like a default config like so to every project

```
  # module.prod_project["whattrainisitnow"].google_logging_project_bucket_config.project will be created
  + resource "google_logging_project_bucket_config" "project" {
      + bucket_id        = "_Default"
      + description      = (known after apply)
      + enable_analytics = false
      + id               = (known after apply)
      + lifecycle_state  = (known after apply)
      + location         = "global"
      + name             = (known after apply)
      + project          = "moz-fx-whattrainisitnow-prod"
      + retention_days   = 30
    }
```

Is that what you mean?

2023-10-19 15:23 UTC, jasonthomas commented
Yes, that's what I mean. Thanks for testing.

2023-10-19 15:25 UTC, jasonthomas requested changes

2023-10-19 15:25 UTC, jasonthomas commented on google_project/main.tf
> +  count            = var.log_analytics ? 1 : 0
Per the previous comment, let's remove this so we define this resource for all projects.

2023-10-19 17:56 UTC, jasonthomas commented on google_project/main.tf
> +  count            = var.log_analytics ? 1 : 0
```suggestion

```

2023-10-23 11:12 UTC, jasonthomas approved these changes

2023-10-23 14:27 UTC, merged